### ISSUE TITLE
Adding BrowserSync to gulpfile.js 

### ISSUE THREAD

**Issue by JeffWeim** [mweimer/LookAtMeRun#1]
https://github.com/gulpjs/gulp/blob/master/docs/recipes/server-with-livereload-and-css-injection.md

This would enable for live-reloading of the server each time a file is saved. Also, allows for css injection which doesn't require a server reload on saving a css file. This would make development a little quicker...

**Comment by mweimer** [comment]
Just run:

```Bash
gulp watch
```

When it sees a source file has changed, it will re-run the build process. The only thing you need to restart the server for is if you change server.js
